# Generated by Django 4.2 on 2023-04-07 00:36

import app.models
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cadastro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('data_de_nascimento', models.DateField()),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('telefone', models.CharField(max_length=50)),
                ('cpf', app.models.CPFField(max_length=14, unique=True, verbose_name='cpf')),
                ('foto', models.ImageField(upload_to='images/')),
                ('data_de_cadastro', models.DateTimeField(default=django.utils.timezone.now)),
                ('data_de_alteracao', models.DateField(auto_now=True)),
            ],
        ),
    ]
